=== sourcegit-scm/sourcegit-theme/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
    "title": "SourceGit Theme",
    "description": "A SourceGit Theme Definition",
    "type": "object",
    "additionalProperties": false,
    "definitions": {
        "color": {
            "type": "string",
            "pattern": "^#[0-9a-fA-F]{6,8}$"
        }
    },
    "properties": {
        "Version": {
            "type": "string",
            "pattern": "^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$",
            "minLength": 1,
            "description": "Theme definition format version"
        },
        "Name": {
            "type": "string",
            "minLength": 1,
            "description": "Display name of the theme"
        },
        "Author": {
            "type": "string",
            "minLength": 1,
            "description": "Author of the theme"
        },
        "Url": {
            "type": "string",
            "format": "uri",
            "pattern": "^https?://",
            "minLength": 1,
            "description": "URL of the author or of the upstream theme this one is based on"
        },
        "BasicColors": {
            "type": "object",
            "properties": {
                "Window": {
                    "$ref": "#/definitions/color",
                    "description": "Window background color"
                },
                "WindowBorder": {
                    "$ref": "#/definitions/color",
                    "description": "Window border color. Only used on Linux."
                },
                "TitleBar": {
                    "$ref": "#/definitions/color",
                    "description": "Title bar background color."
                },
                "ToolBar": {
                    "$ref": "#/definitions/color",
                    "description": "Tool bar background color"
                },
                "Popup": {
                    "$ref": "#/definitions/color",
                    "description": "Popup/ContextMenu panel background color"
                },
                "PopupBorder": {
                    "$ref": "#/definitions/color",
                    "description": "Popup/ContextMenu panel border color"
                },
                "Contents": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used in inputs, data grids, file content viewer, change lists, text diff viewer, etc."
                },
                "Badge": {
                    "$ref": "#/definitions/color",
                    "description": "Badge background color"
                },
                "BadgeFG": {
                    "$ref": "#/definitions/color",
                    "description": "Badge foreground color"
                },
                "Conflict": {
                    "$ref": "#/definitions/color",
                    "description": "Conflict panel background color"
                },
                "Conflict.Foreground": {
                    "$ref": "#/definitions/color",
                    "description": "Conflict panel foreground color"
                },
                "Conflict.MineBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color of 'Mine' section in merge conflict editor"
                },
                "Conflict.TheirsBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color of 'Theirs' section in merge conflict editor"
                },
                "Border0": {
                    "$ref": "#/definitions/color",
                    "description": "Border color used in some controls, like Window, Tab, Toolbar, etc."
                },
                "Border1": {
                    "$ref": "#/definitions/color",
                    "description": "Border color used in inputs, like TextBox, ComboBox, etc."
                },
                "Border2": {
                    "$ref": "#/definitions/color",
                    "description": "Border color used in visual lines, like seperators, Rectange, etc."
                },
                "FlatButton.Background": {
                    "$ref": "#/definitions/color",
                    "description": "Flat button background color, like `Cancel`, `Commit & Push` button"
                },
                "FlatButton.BackgroundHovered": {
                    "$ref": "#/definitions/color",
                    "description": "Flat button background color when hovered, like `Cancel` button"
                },
                "FlatButton.FloatingBorder": {
                    "$ref": "#/definitions/color",
                    "description": "Flat button (floating) border color. Used by hunk action buttons such as `Stage`/`Discard`/`Unstage`"
                },
                "FG1": {
                    "$ref": "#/definitions/color",
                    "description": "Primary foreground color for all text elements"
                },
                "FG2": {
                    "$ref": "#/definitions/color",
                    "description": "Secondary foreground color for all text elements"
                },
                "Diff.EmptyBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used in empty lines in diff viewer"
                },
                "Diff.AddedBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used in added lines in diff viewer"
                },
                "Diff.DeletedBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used in deleted lines in diff viewer"
                },
                "Diff.AddedHighlight": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used for changed words in added lines in diff viewer"
                },
                "Diff.DeletedHighlight": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used for changed words in deleted lines in diff viewer"
                },
                "Diff.BlockBorderHighlight": {
                    "$ref": "#/definitions/color",
                    "description": "Border color used for highlighting current changed blocks in diff viewer"
                },
                "SystemAccentColor": {
                    "$ref": "#/definitions/color",
                    "description": "Accent color for selected items"
                },
                "Link": {
                    "$ref": "#/definitions/color",
                    "description": "Color for issue links"
                },
                "InlineCode": {
                    "$ref": "#/definitions/color",
                    "description": "Background color for inline code in commit messages"
                },
                "InlineCodeFG": {
                    "$ref": "#/definitions/color",
                    "description": "Foreground color for inline code in commit messages"
                },
                "HistoryBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color for history view (not including data grid background)"
                }
            }
        },
        "GraphPenThickness": {
            "type": "number",
            "minimum": 1,
            "maximum": 4,
            "description": "Thickness of pens to draw commit graph"
        },
        "OpacityForNotMergedCommits": {
            "type": "number",
            "minimum": 0.1,
            "maximum": 1,
            "description": "Opacity for commits that not belongs (haven't been merged) to current branch in histories view"
        },
        "UseMicaOnWindows11": {
            "type": "boolean",
            "description": "Whether to use Mica material on Windows 11"
        },
        "GraphColors": {
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "#/definitions/color"
            },
            "description": "Array of colors used to draw the commit graph"
        }
    }
}

=== sourcegit-scm/sourcegit-theme/themes/AyuDark/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Ayu Dark",
  "Author": "@Hectoralvf",
  "Url": "https://codeberg.org/hectoralvf",
  "BasicColors": {
    "Window": "#0d1017",
    "WindowBorder": "#0d1017",
    "TitleBar": "#171b24",
    "ToolBar": "#14171f",
    "Popup": "#1c212b",
    "Contents": "#0d1017",
    "Badge": "#e6b450",
    "BadgeFG": "#000000",
    "Border0": "#1f2430",
    "Border1": "#1f2430",
    "Border2": "#a2a9b12e",
    "FlatButton.Background": "#0d1017",
    "FlatButton.BackgroundHovered": "#1f2430",
    "FG1": "#cccac2",
    "FG2": "#bfbdb6",
    "Diff.EmptyBG": "#14171f",
    "Diff.AddedBG": "#87d96c1f",
    "Diff.DeletedBG": "#f279831f",
    "Diff.AddedHighlight": "#87d96c",
    "Diff.DeletedHighlight": "#f27983",
    "SystemAccentColor": "#e6b450",
    "HistoryBG": "#0d1017"
  },
  "OpacityForNotMergedCommits": 0.4,
  "GraphColors": [
    "#ea6c73",
    "#f29668",
    "#e6b450",
    "#87d96c",
    "#cda1fa"
  ]
}

=== sourcegit-scm/sourcegit-theme/themes/TokyoNight.json
{
  "BasicColors": {
    "Window": "#1a1b26",
    "WindowBorder": "#292e42",
    "TitleBar": "#1a1b26",
    "ToolBar": "#1a1b26",
    "Popup": "#1a1b26",
    "Contents": "#1a1b26",
    "HistoryBG": "#1a1b26",

    "Badge": "#f7768e",
    "BadgeFG": "#1a1b26",
    "Conflict": "#f7768e",
    "Conflict.Foreground": "#1a1b26",

    "Border0": "#292e42",
    "Border1": "#3b4261",
    "Border2": "#565f89",

    "FlatButton.Background": "#292e42",
    "FlatButton.BackgroundHovered": "#3b4261",

    "FG1": "#c0caf5",
    "FG2": "#a9b1d6",

    "Diff.EmptyBG": "#1a1b26",

    "Diff.AddedBG": "#2e3f3a",
    "Diff.AddedHighlight": "#3a534b",

    "Diff.DeletedBG": "#4b2230",
    "Diff.DeletedHighlight": "#5a2a39",

    "SystemAccentColor": "#7aa2f7",
    "Link": "#7aa2f7"
  },

  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.5,

  "GraphColors": [
    "#bb9af7",
    "#f7768e",
    "#ff9e64",
    "#e0af68",
    "#9ece6a",
    "#73daca",
    "#7aa2f7",
    "#b4f9f8"
  ]
}

=== sourcegit-scm/sourcegit-theme/themes/Squid.json
{
    "BasicColors": {
        "Window": "#282A32",
        "WindowBorder": "#1E1F22",
        "TitleBar": "#282D35",
        "ToolBar": "#313741",
        "Popup": "#32363F",
        "Contents": "#1C1E23",
        "HistoryBG": "#282A32",
        "Badge": "#777782",
        "BadgeFG": "#FFFFFF",
        "Conflict": "#906A38",
        "Conflict.Foreground": "#E4DACF",
        "Border0": "#1E1F22",
        "Border1": "#3E444D",
        "Border2": "#3E444D",
        "FlatButton.Background": "#32363F",
        "FlatButton.BackgroundHovered": "#3E444D",
        "FG1": "#FFFFFF",
        "FG2": "#C9CACB",
        "Diff.EmptyBG": "#1C1E23",
        "Diff.AddedBG": "#26352C",
        "Diff.DeletedBG": "#392528",
        "Diff.AddedHighlight": "#314F37",
        "Diff.DeletedHighlight": "#592B2D",
        "SystemAccentColor": "#2D4676"
    },
    "GraphPenThickness": 1,
    "OpacityForNotMergedCommits": 0.6,
    "GraphColors": [
        "#16A0C0",
        "#0A69F7",
        "#8E00C2",
        "#C517B7",
        "#D90171",
        "#CD0102",
        "#F25D2E",
        "#F2CB33",
        "#7BD939"
    ]
}

=== sourcegit-scm/sourcegit-theme/themes/JetBrainsDark_DiffHighContrast/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "JetBrains Dark Diff High Contrast",
  "Author": "@MelonHell",
  "Url": "https://gist.github.com/MelonHell",
  "BasicColors": {
    "Window": "#2b2d30",
    "WindowBorder": "#2b2d30",
    "TitleBar": "#222426",
    "ToolBar": "#2b2d30",
    "Popup": "#2b2d30",
    "Contents": "#1e1f22",
    "HistoryBG": "#2b2d30",
    "Badge": "#3574f0",
    "BadgeFG": "#ffffff",
    "Conflict": "#45302b",
    "Conflict.Foreground": "#ced0d6",
    "Border0": "#1e1f22",
    "Border1": "#4e5157",
    "Border2": "#4e5157",
    "FlatButton.Background": "#2b2d30",
    "FlatButton.BackgroundHovered": "#393b40",
    "FG1": "#ced0d6",
    "FG2": "#808080",
    "Diff.EmptyBG": "#101010",
    "Diff.AddedBG": "#1c322b",
    "Diff.DeletedBG": "#412323",
    "Diff.AddedHighlight": "#265444",
    "Diff.DeletedHighlight": "#883838"
  },
  "GraphPenThickness": 2,
  "GraphColors": [
    "#FF15A0BF",
    "#FF0669F7",
    "#FF8E00C2",
    "#FFC517B6",
    "#FFD90171",
    "#FFCD0101",
    "#FFF25D2E",
    "#FFF2CA33",
    "#FF7BD938",
    "#FF2ECE9D"
  ]
}

=== sourcegit-scm/sourcegit-theme/themes/Eldritch_Cthulhu/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Eldritch Cthulhu",
  "Author": "@eldritch-theme",
  "Url": "https://github.com/eldritch-theme",
  "BasicColors": {
    "Window": "#212337",
    "WindowBorder": "#212337",
    "TitleBar": "#323449",
    "ToolBar": "#212337",
    "Popup": "#5b5c66",
    "PopupBorder": "#323449",
    "Contents": "#212337",
    "HistoryBG": "#212337",
    "Badge": "#f16c75",
    "BadgeFG": "#ebfafa",
    "Conflict": "#f16c75",
    "Conflict.Foreground": "#ebfafa",
    "Conflict.MineBG": "#254c4a",
    "Conflict.TheirsBG": "#303555",
    "Border0": "#323449",
    "Border1": "#454759",
    "Border2": "#323449",
    "FlatButton.Background": "#323449",
    "FlatButton.BackgroundHovered": "#454759",
    "FlatButton.FloatingBorder": "#37f499",
    "FG1": "#ebfafa",
    "FG2": "#7081d0",
    "Diff.EmptyBG": "#212337",
    "Diff.AddedBG": "#254c4a",
    "Diff.DeletedBG": "#4a3143",
    "Diff.AddedHighlight": "#29765e",
    "Diff.DeletedHighlight": "#74404f",
    "Diff.BlockBorderHighlight": "#37f499",
    "SystemAccentColor": "#37f499",
    "Link": "#04d1f9",
    "InlineCode": "#454759",
    "InlineCodeFG": "#ebfafa"
  },
  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.5,
  "GraphColors": [
    "#f16c75",
    "#f7c67f",
    "#f1fc79",
    "#37f499",
    "#04d1f9",
    "#f265b5",
    "#a48cf2",
    "#7081d0"
  ]
}

=== sourcegit-scm/sourcegit-theme/themes/Catpuccin_Latte/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Catpuccin Latte",
  "Author": "@eljoth",
  "Url": "https://github.com/eljoth",
  "BasicColors": {
    "Window": "#eff1f5",
    "WindowBorder": "#e6e9ef",
    "TitleBar": "#e6e9ef",
    "ToolBar": "#e6e9ef",
    "Popup": "#eff1f5",
    "PopupBorder": "#dce0e8",
    "Contents": "#e6e9ef",
    "HistoryBG": "#eff1f5",
    "Badge": "#1e66f5",
    "BadgeFG": "#eff1f5",
    "Conflict": "#e8c1c3",
    "Conflict.Foreground": "#d20f39",
    "Conflict.MineBG": "#4040a02b",
    "Conflict.TheirsBG": "#40d20f39",
    "Border0": "#bcc0cc",
    "Border1": "#bcc0cc",
    "Border2": "#acb0be",
    "FlatButton.Background": "#e6e9ef",
    "FlatButton.BackgroundHovered": "#dce0e8",
    "FlatButton.FloatingBorder": "#bcc0cc",
    "FG1": "#4c4f69",
    "FG2": "#6c6f85",
    "Diff.EmptyBG": "#eff1f5",
    "Diff.BlockBorderHighlight": "#1e66f5",
    "Diff.AddedBG": "#d1e8d4",
    "Diff.DeletedBG": "#e8c1c3",
    "Diff.AddedHighlight": "#6640a02b",
    "Diff.DeletedHighlight": "#dd7878",
    "SystemAccentColor": "#7287fd",
    "Link": "#1e66f5",
    "InlineCode": "#ccd0da",
    "InlineCodeFG": "#4c4f69"
  },
  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.5,
  "GraphColors": [
    "#1e66f5",
    "#179299",
    "#40a02b",
    "#df8e1d",
    "#fe640b",
    "#d20f39"
  ]
}

=== sourcegit-scm/sourcegit-theme/themes/TokyoNight_Storm.json
{
  "BasicColors": {
    "Window": "#24283b",
    "WindowBorder": "#414868",
    "TitleBar": "#24283b",
    "ToolBar": "#24283b",
    "Popup": "#24283b",
    "Contents": "#24283b",
    "HistoryBG": "#24283b",

    "Badge": "#f7768e",
    "BadgeFG": "#24283b",
    "Conflict": "#f7768e",
    "Conflict.Foreground": "#24283b",

    "Border0": "#414868",
    "Border1": "#545c7e",
    "Border2": "#737aa2",

    "FlatButton.Background": "#414868",
    "FlatButton.BackgroundHovered": "#545c7e",

    "FG1": "#c0caf5",
    "FG2": "#a9b1d6",

    "Diff.EmptyBG": "#24283b",

    "Diff.AddedBG": "#283b4d",
    "Diff.AddedHighlight": "#324a61",

    "Diff.DeletedBG": "#4b2230",
    "Diff.DeletedHighlight": "#5a2a39",

    "SystemAccentColor": "#7aa2f7",
    "Link": "#7aa2f7"
  },

  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.5,

  "GraphColors": [
    "#bb9af7",
    "#f7768e",
    "#ff9e64",
    "#e0af68",
    "#9ece6a",
    "#73daca",
    "#7aa2f7",
    "#b4f9f8"
  ]
}

=== sourcegit-scm/sourcegit-theme/themes/Solarized_Dark/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Solarized Dark",
  "Author": "Ethan Schoonover",
  "Url": "https://ethanschoonover.com/solarized/",
  "BasicColors": {
    "Window": "#002b36",
    "WindowBorder": "#002b36",
    "TitleBar": "#073642",
    "ToolBar": "#002b36",
    "Popup": "#073642",
    "Contents": "#073642",
    "HistoryBG": "#01303c",
    "Badge": "#268bd2",
    "BadgeFG": "#fdf6e3",
    "Conflict": "#5c3928",
    "Conflict.Foreground": "#dc322f",
    "Border0": "#073642",
    "Border1": "#073642",
    "Border2": "#073642",
    "FlatButton.Background": "#073642",
    "FlatButton.BackgroundHovered": "#0b3d49",
    "FG1": "#93a1a1",
    "FG2": "#839496",
    "Diff.EmptyBG": "#002b36",
    "Diff.AddedBG": "#173f35",
    "Diff.DeletedBG": "#4b2c2c",
    "Diff.AddedHighlight": "#235444",
    "Diff.DeletedHighlight": "#653636",
    "SystemAccentColor": "#268bd2",
    "Link": "#268bd2",
    "InlineCode": "#30ffffff",
    "InlineCodeFG": "#d7ba7d"
  },
  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.4,
  "GraphColors": [
    "#268bd2",
    "#2aa198",
    "#859900",
    "#b58900",
    "#cb4b16",
    "#d33682"
  ]
}
