=== sourcegit-scm/sourcegit-theme/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
    "title": "SourceGit Theme",
    "description": "A SourceGit Theme Definition",
    "type": "object",
    "additionalProperties": false,
    "definitions": {
        "color": {
            "type": "string",
            "pattern": "^#[0-9a-fA-F]{6,8}$"
        }
    },
    "properties": {
        "Version": {
            "type": "string",
            "pattern": "^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$",
            "minLength": 1,
            "description": "Theme definition format version"
        },
        "Name": {
            "type": "string",
            "minLength": 1,
            "description": "Display name of the theme"
        },
        "Author": {
            "type": "string",
            "minLength": 1,
            "description": "Author of the theme"
        },
        "Url": {
            "type": "string",
            "format": "uri",
            "pattern": "^https?://",
            "minLength": 1,
            "description": "URL of the author or of the upstream theme this one is based on"
        },
        "BasicColors": {
            "type": "object",
            "properties": {
                "Window": {
                    "$ref": "#/definitions/color",
                    "description": "Window background color"
                },
                "WindowBorder": {
                    "$ref": "#/definitions/color",
                    "description": "Window border color. Only used on Linux."
                },
                "TitleBar": {
                    "$ref": "#/definitions/color",
                    "description": "Title bar background color."
                },
                "ToolBar": {
                    "$ref": "#/definitions/color",
                    "description": "Tool bar background color"
                },
                "Popup": {
                    "$ref": "#/definitions/color",
                    "description": "Popup/ContextMenu panel background color"
                },
                "PopupBorder": {
                    "$ref": "#/definitions/color",
                    "description": "Popup/ContextMenu panel border color"
                },
                "Contents": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used in inputs, data grids, file content viewer, change lists, text diff viewer, etc."
                },
                "Badge": {
                    "$ref": "#/definitions/color",
                    "description": "Badge background color"
                },
                "BadgeFG": {
                    "$ref": "#/definitions/color",
                    "description": "Badge foreground color"
                },
                "Conflict": {
                    "$ref": "#/definitions/color",
                    "description": "Conflict panel background color"
                },
                "Conflict.Foreground": {
                    "$ref": "#/definitions/color",
                    "description": "Conflict panel foreground color"
                },
                "Conflict.MineBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color of 'Mine' section in merge conflict editor"
                },
                "Conflict.TheirsBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color of 'Theirs' section in merge conflict editor"
                },
                "Border0": {
                    "$ref": "#/definitions/color",
                    "description": "Border color used in some controls, like Window, Tab, Toolbar, etc."
                },
                "Border1": {
                    "$ref": "#/definitions/color",
                    "description": "Border color used in inputs, like TextBox, ComboBox, etc."
                },
                "Border2": {
                    "$ref": "#/definitions/color",
                    "description": "Border color used in visual lines, like seperators, Rectange, etc."
                },
                "FlatButton.Background": {
                    "$ref": "#/definitions/color",
                    "description": "Flat button background color, like `Cancel`, `Commit & Push` button"
                },
                "FlatButton.BackgroundHovered": {
                    "$ref": "#/definitions/color",
                    "description": "Flat button background color when hovered, like `Cancel` button"
                },
                "FlatButton.FloatingBorder": {
                    "$ref": "#/definitions/color",
                    "description": "Flat button (floating) border color. Used by hunk action buttons such as `Stage`/`Discard`/`Unstage`"
                },
                "FG1": {
                    "$ref": "#/definitions/color",
                    "description": "Primary foreground color for all text elements"
                },
                "FG2": {
                    "$ref": "#/definitions/color",
                    "description": "Secondary foreground color for all text elements"
                },
                "Diff.EmptyBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used in empty lines in diff viewer"
                },
                "Diff.AddedBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used in added lines in diff viewer"
                },
                "Diff.DeletedBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used in deleted lines in diff viewer"
                },
                "Diff.AddedHighlight": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used for changed words in added lines in diff viewer"
                },
                "Diff.DeletedHighlight": {
                    "$ref": "#/definitions/color",
                    "description": "Background color used for changed words in deleted lines in diff viewer"
                },
                "Diff.BlockBorderHighlight": {
                    "$ref": "#/definitions/color",
                    "description": "Border color used for highlighting current changed blocks in diff viewer"
                },
                "SystemAccentColor": {
                    "$ref": "#/definitions/color",
                    "description": "Accent color for selected items"
                },
                "Link": {
                    "$ref": "#/definitions/color",
                    "description": "Color for issue links"
                },
                "InlineCode": {
                    "$ref": "#/definitions/color",
                    "description": "Background color for inline code in commit messages"
                },
                "InlineCodeFG": {
                    "$ref": "#/definitions/color",
                    "description": "Foreground color for inline code in commit messages"
                },
                "HistoryBG": {
                    "$ref": "#/definitions/color",
                    "description": "Background color for history view (not including data grid background)"
                }
            }
        },
        "GraphPenThickness": {
            "type": "number",
            "minimum": 1,
            "maximum": 4,
            "description": "Thickness of pens to draw commit graph"
        },
        "OpacityForNotMergedCommits": {
            "type": "number",
            "minimum": 0.1,
            "maximum": 1,
            "description": "Opacity for commits that not belongs (haven't been merged) to current branch in histories view"
        },
        "UseMicaOnWindows11": {
            "type": "boolean",
            "description": "Whether to use Mica material on Windows 11"
        },
        "GraphColors": {
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "#/definitions/color"
            },
            "description": "Array of colors used to draw the commit graph"
        }
    }
}

=== sourcegit-scm/sourcegit-theme/themes/Catpuccin_Frappe/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Catpuccin Frappe",
  "Author": "@eljoth",
  "Url": "https://github.com/eljoth",
  "BasicColors": {
    "Window": "#303446",
    "WindowBorder": "#313244",
    "TitleBar": "#303446",
    "ToolBar": "#303446",
    "Popup": "#303446",
    "Contents": "#303446",
    "HistoryBG": "#303446",

    "Badge": "#f2cdcd",
    "BadgeFG": "#303446",
    "Conflict": "#c45a5f",
    "Conflict.Foreground": "#303446",

    "Border0": "#313244",
    "Border1": "#313244",
    "Border2": "#313244",

    "FlatButton.Background": "#313244",
    "FlatButton.BackgroundHovered": "#45475a",

    "FG1": "#c6d0f5",
    "FG2": "#b5bfe2",

    "Diff.EmptyBG": "#303446",

    "Diff.AddedBG": "#4f6b52",
    "Diff.AddedHighlight": "#5b7a5f",

    "Diff.DeletedBG": "#7f3a3f",
    "Diff.DeletedHighlight": "#8f4248",

    "SystemAccentColor": "#f2cdcd",
    "Link": "#8caaee"
  },

  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.5,
  "GraphColors": [
    "#f2cdcd",
    "#f5bde6",
    "#f5a97f",
    "#cecacd",
    "#abd18f",
    "#8caaee"
  ]
}

=== sourcegit-scm/sourcegit-theme/themes/Panda/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Panda",
  "Author": "@WTFive",
  "Url": "https://github.com/wtfive",
  "BasicColors": {
    "Window": "#292A2B",
    "WindowBorder": "#222223",
    "TitleBar": "#31353a",
    "ToolBar": "#292A2B",
    "Popup": "#242526",
    "Contents": "#242526",
    "HistoryBG": "#292A2B",
    "Badge": "#FFB86C",
    "BadgeFG": "#ffffff",
    "Conflict": "#FFB86C",
    "Conflict.Foreground": "#E6E6E6",
    "Border0": "#222223",
    "Border1": "#31353a",
    "Border2": "#373B41",
    "FlatButton.Background": "#292A2B",
    "FlatButton.BackgroundHovered": "#3E4250",
    "FG1": "#E6E6E6",
    "FG2": "#BBBBBB",
    "Diff.EmptyBG": "#31353a",
    "Diff.AddedBG": "#074b41",
    "Diff.DeletedBG": "#4c2336",
    "Diff.AddedHighlight": "#0f9582",
    "Diff.DeletedHighlight": "#cc5e91",
    "SystemAccentColor": "#14c7ad",
    "Link": "#B084EB"
  },
  "OpacityForNotMergedCommits": 0.7,
  "GraphColors": [
    "#FF75B5",
    "#19f9d8",
    "#FFB86C",
    "#45A9F9",
    "#FF2C6D",
    "#B084EB",
    "#FF9AC1",
    "#6FE7D2",
    "#FF4B82",
    "#FFB86C"
  ]
}

=== sourcegit-scm/sourcegit-theme/themes/AdwaitaLight.json
{
  "BasicColors": {
    "Window": "#ffffff",
    "WindowBorder": "#d5d5d7",
    "TitleBar": "#ffffff",
    "ToolBar": "#fafafb",
    "Popup": "#fafafb",
    "Contents": "#fafafb",
    "Badge": "#FFB0CEE8",
    "BadgeFG": "#FF1F1F1F",
    "Conflict": "#cce1ff",
    "Conflict.Foreground": "#99c1f1",
    "Border0": "#d5d5d7",
    "Border1": "#d5d5d7",
    "Border2": "#d5d5d7",
    "FlatButton.Background": "#e6e6e7",
    "FlatButton.BackgroundHovered": "#bebec0",
    "FG1": "#2f2f33",
    "FG2": "#2f2f33",
    "Diff.EmptyBG": "#99C1F1",
    "Diff.AddedBG": "#dcffdc",
    "Diff.DeletedBG": "#ffdcdc",
    "Diff.AddedHighlight": "#99ff99",
    "Diff.DeletedHighlight": "#ff9999",
    "SystemAccentColor": "#6f8396",
    "Link": "#1c71d7",
    "HistoryBG": "#ffffff"
  },
  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.5,
  "GraphColors": [
    "#99C1F1",
    "#8FF0A4",
    "#F9F06B",
    "#FFBE6F",
    "#F66151",
    "#DC8ADD",
    "#CDAB8F",
    "#1A5FB4",
    "#26A269",
    "#E5A50A",
    "#C64600",
    "#A51D2D",
    "#613583",
    "#63452C",
    "#DEDDDA"
  ]
}

=== sourcegit-scm/sourcegit-theme/themes/TokyoNight_Light/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "TokyoNight Light",
  "Author": "tokyo-night",
  "Url": "https://github.com/tokyo-night/tokyo-night-vscode-theme",
  "BasicColors": {
    "Window": "#d5d6db",
    "WindowBorder": "#b4b5b9",
    "TitleBar": "#d5d6db",
    "ToolBar": "#d5d6db",
    "Popup": "#d5d6db",
    "Contents": "#d5d6db",
    "HistoryBG": "#d5d6db",

    "Badge": "#f52a65",
    "BadgeFG": "#d5d6db",
    "Conflict": "#f52a65",
    "Conflict.Foreground": "#d5d6db",

    "Border0": "#b4b5b9",
    "Border1": "#a8aecb",
    "Border2": "#8c92ad",

    "FlatButton.Background": "#b4b5b9",
    "FlatButton.BackgroundHovered": "#a8aecb",

    "FG1": "#343b58",
    "FG2": "#565a6e",

    "Diff.EmptyBG": "#d5d6db",

    "Diff.AddedBG": "#cdeff0",
    "Diff.AddedHighlight": "#bfe3e6",

    "Diff.DeletedBG": "#f3d5d9",
    "Diff.DeletedHighlight": "#eabfc6",

    "SystemAccentColor": "#34548a",
    "Link": "#34548a"
  },

  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.5,

  "GraphColors": [
    "#5a4a78",
    "#f52a65",
    "#b15c00",
    "#8f5e15",
    "#587539",
    "#0f4b6e",
    "#34548a",
    "#166775"
  ]
}

=== sourcegit-scm/sourcegit-theme/themes/Solarized_Dark_Bordered/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Solarized Dark Bordered",
  "Author": "Ethan Schoonover",
  "Url": "https://ethanschoonover.com/solarized/",
  "BasicColors": {
    "Window": "#002b36",
    "WindowBorder": "#002b36",
    "TitleBar": "#073642",
    "ToolBar": "#002b36",
    "Popup": "#073642",
    "PopupBorder": "#3a5a64",
    "Contents": "#073642",
    "HistoryBG": "#01303c",
    "Badge": "#268bd2",
    "BadgeFG": "#fdf6e3",
    "Conflict": "#5c3928",
    "Conflict.Foreground": "#dc322f",
    "Border0": "#204f5f",
    "Border1": "#25596a",
    "Border2": "#204f5f",
    "FlatButton.Background": "#073642",
    "FlatButton.BackgroundHovered": "#0b3d49",
    "FlatButton.FloatingBorder": "#25596a",
    "FG1": "#93a1a1",
    "FG2": "#839496",
    "Diff.EmptyBG": "#002b36",
    "Diff.AddedBG": "#173f35",
    "Diff.DeletedBG": "#4b2c2c",
    "Diff.AddedHighlight": "#235444",
    "Diff.DeletedHighlight": "#653636",
    "SystemAccentColor": "#268bd2",
    "Link": "#268bd2",
    "InlineCode": "#30ffffff",
    "InlineCodeFG": "#d7ba7d"
  },
  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.4,
  "GraphColors": [
    "#268bd2",
    "#2aa198",
    "#859900",
    "#b58900",
    "#cb4b16",
    "#d33682"
  ]
}

=== sourcegit-scm/sourcegit-theme/themes/Solarized_Dark.json
{
  "BasicColors": {
    "Window": "#002b36",
    "WindowBorder": "#002b36",
    "TitleBar": "#073642",
    "ToolBar": "#002b36",
    "Popup": "#073642",
    "Contents": "#073642",
    "HistoryBG": "#073642",
    "Badge": "#268bd2",
    "BadgeFG": "#fdf6e3",
    "Conflict": "#5c3928",
    "Conflict.Foreground": "#dc322f",
    "Border0": "#073642",
    "Border1": "#073642",
    "Border2": "#073642",
    "FlatButton.Background": "#073642",
    "FlatButton.BackgroundHovered": "#0b3d49",
    "FG1": "#93a1a1",
    "FG2": "#839496",
    "Diff.EmptyBG": "#002b36",
    "Diff.AddedBG": "#173f35",
    "Diff.DeletedBG": "#4b2c2c",
    "Diff.AddedHighlight": "#235444",
    "Diff.DeletedHighlight": "#653636",
    "SystemAccentColor": "#268bd2",
    "Link": "#268bd2"
  },
  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.4,
  "GraphColors": [
    "#268bd2",
    "#2aa198",
    "#859900",
    "#b58900",
    "#cb4b16",
    "#d33682"
  ]
}

=== sourcegit-scm/sourcegit-theme/themes/Catpuccin_Macchiato.json
{
  "BasicColors": {
    "Window": "#24273a",
    "WindowBorder": "#363a4f",
    "TitleBar": "#1e2030",
    "ToolBar": "#1e2030",
    "Popup": "#24273a",
    "Contents": "#363a4f",
    "HistoryBG": "#24273a",

    "Badge": "#8aadf4",
    "BadgeFG": "#1e2030",
    "Conflict": "#c24f5f",
    "Conflict.Foreground": "#1e2030",

    "Border0": "#363a4f",
    "Border1": "#494d64",
    "Border2": "#5b6078",

    "FlatButton.Background": "#363a4f",
    "FlatButton.BackgroundHovered": "#494d64",

    "FG1": "#cad3f5",
    "FG2": "#b8c0e0",

    "Diff.EmptyBG": "#363a4f",

    "Diff.AddedBG": "#425f55",
    "Diff.AddedHighlight": "#4f7266",

    "Diff.DeletedBG": "#7a3942",
    "Diff.DeletedHighlight": "#8a414c",

    "SystemAccentColor": "#8aadf4",
    "Link": "#8aadf4"
  },

  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.5,
  "GraphColors": ["#8aadf4", "#ed8796", "#a6da95", "#f5a97f", "#c6a0f6"]
}

=== sourcegit-scm/sourcegit-theme/themes/Solarized_Light/theme.json
{
  "$schema": "https://sourcegit-scm.github.io/sourcegit-theme.schema.json",
  "Version": "1.0",
  "Name": "Solarized Light",
  "Author": "Ethan Schoonover",
  "Url": "https://ethanschoonover.com/solarized/",
  "BasicColors": {
    "Window": "#fdf6e3",
    "WindowBorder": "#fdf6e3",
    "TitleBar": "#eee8d5",
    "ToolBar": "#fdf6e3",
    "Popup": "#fdf6e3",
    "Contents": "#eee8d5",
    "HistoryBG": "#faf3e0",
    "Badge": "#268bd2",
    "BadgeFG": "#fdf6e3",
    "Conflict": "#f7d8c4",
    "Conflict.Foreground": "#dc322f",
    "Border0": "#eee8d5",
    "Border1": "#eee8d5",
    "Border2": "#eee8d5",
    "FlatButton.Background": "#fdf6e3",
    "FlatButton.BackgroundHovered": "#eee8d5",
    "FG1": "#586e75",
    "FG2": "#657b83",
    "Diff.EmptyBG": "#eee8d5",
    "Diff.AddedBG": "#e0ead6",
    "Diff.DeletedBG": "#f3d6c8",
    "Diff.AddedHighlight": "#cbdcab",
    "Diff.DeletedHighlight": "#eeb9a6",
    "SystemAccentColor": "#268bd2",
    "Link": "#268bd2",
    "InlineCode": "#d1cbba",
    "InlineCodeFG": "#cf8806"
  },
  "GraphPenThickness": 2,
  "OpacityForNotMergedCommits": 0.4,
  "GraphColors": [
    "#268bd2",
    "#2aa198",
    "#859900",
    "#b58900",
    "#cb4b16",
    "#d33682"
  ]
}
